openapi: 3.0.0
info:
  title: sample
  version: 1.sample0
  contact: {}
  description: sample
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
      operationId: get-users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      description: ''
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  '':
                    type: string
          headers: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
        description: ''
      description: POST /users
      tags:
        - users
  /shops:
    get:
      summary: shops
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
      operationId: get-shops
components:
  schemas: {}
  securitySchemes: {}
