openapi: 3.0.0
info:
  title: sample
  version: '1.0'
  contact: {}
  description: sample
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
      operationId: get-users
components:
  schemas: {}
  securitySchemes: {}
