openapi: 3.0.0
info:
  title: sample
  version: 1
  contact: {}
  description: sample
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: GET /users
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
      operationId: get-users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      description: GET /users
    post:
      summary: POST /users
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
          headers: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
        description: ''
      description: POST /users
      tags:
        - users
  /shops:
    get:
      summary: GET /shops
      tags:
        - shop
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  owner:
                    oneOf:
                      - properties:
                          name:
                            type: string
                    type: object
      operationId: get-shops
      description: GET /shops
    post:
      summary: POST /shops
      operationId: post-shops
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
      description: POST /shops
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      tags:
        - shop
components:
  schemas: {}
  securitySchemes: {}
